### ISSUE TITLE
BUG incompatibility kirby 3.3

### ISSUE THREAD

**Issue by darylcre8iv** [mullema/k3-panel-view-extended#8] opened 2019-11-12 04:19 UTC
when upgrading websites to kirby 3.3.0, the settings that supposed to be hidden are showing in the panel it also has a message prompt that there is something wrong.

steps to reproduce the issue:
- install plainkit with a kirby 3.3.0
- install view-extended with a version 2.2

result : display an alert message (different message on various browser) and displaying settings thats intended to be hidden

we are using the code below to hide the settings in a page
```
options:
  hideSettings: true
```

**Comment by mullema** [comment] 2019-11-12 09:34
Hi @darylcre8iv 
Thank you for your report.
I am not able to reproduce your issue with Kirby 3.3.0 / k3-panel-view-extended v2.2.0. 

Please provide more information about your setup, other plugins, panel css, panel js, and more details about the error messages.

**Comment by martincre8iv** [comment] 2019-11-13 01:28
Hi @mullema,
I am able to reproduce the issue state by @darylcre8iv here are the steps and screenshots below.

1) Create a new project with composer, using Kirby’s plainkit:
composer create-project getkirby/plainkit plugintest
2)  Install PanelViewExtended:
composer require mullema/k3-panel-view-extended
3) Sign up account
4) Login
after login I got this error every-time I refreshes the panel page
For mozilla 
![mozilla](https://user-images.githubusercontent.com/56704160/68724277-fa23d480-05f5-11ea-95ba-bcc6663dd7af.PNG)

For Safari
<img width="1333" alt="safari" src="https://user-images.githubusercontent.com/56704160/68724550-db720d80-05f6-11ea-8881-096707963e36.png">

For Chrome
![chrome](https://user-images.githubusercontent.com/56704160/68724278-fabc6b00-05f5-11ea-80f1-ad636f5e341f.PNG)

**Comment by mullema** [comment] 2019-11-13 09:49
@darylcre8iv / @martincre8iv Please check v2.2.1, the issue should be fixed.

**Comment by martincre8iv** [comment] 2019-11-13 10:11
Hi @mullema I got another alert message after updating to v2.2.1

for mozilla
![moz](https://user-images.githubusercontent.com/56704160/68754001-e6519000-0640-11ea-9c58-26684f498d18.PNG)

For chrome
![chro](https://user-images.githubusercontent.com/56704160/68754004-e6ea2680-0640-11ea-9f4c-4e40da467561.PNG)

**Comment by mullema** [comment] 2019-11-13 10:22
my bad. check v.2.2.3

**Comment by martincre8iv** [comment] 2019-11-13 10:34
@mullema Great! The issue on the alert message is now fixed. Thank you very much

**Closed** 2019-11-13 13:02 UTC
